[package]
org = "wso2"
name = "tweet_performance_analytics"
version = "0.1.0"
distribution = "2201.10.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "twitter"
version = "0.1.0"
repository = "local"
