[package]
distribution = "2201.12.10"
org = "ballerinax"
name = "twitter"
version = "0.1.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Marketing/Social Media Accounts", "Cost/Freemium"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-twitter"

[build-options]
observabilityIncluded = true
